#ifndef ROTARY_ENCODER_H
#define ROTARY_ENCODER_H

#define ANALOG_PIN_8 0
#define ANALOG_PIN_1 1
#define ANALOG_PIN_2 2

#define PCINT16 ANALOG_PIN_8
#define PCINT17 ANALOG_PIN_1
#define PCINT18 ANALOG_PIN_2

#define ENCODER_DT PCINT16
#define ENCODER_CLK PCINT17
#define ENCODER_SW PCINT18

#define ENCODER_DT_DDR DDRK
#define ENCODER_CLK_DDR DDRK
#define ENCODER_SW_DDR DDRK

#define ENCODER_DT_PORT PORTK
#define ENCODER_CLK_PORT PORTK
#define ENCODER_SW_PORT PORTK

void encoder_init();

#endif //ROTARY_ENCODER_H